import { DEFAULT_WORKSPACE, STORAGE_KEY, effortXP } from './data.js';

const AI_SETTINGS_KEY = 'devtracker:ai-settings:v1';
const DEFAULT_AI_SETTINGS = {
  activeProviderId: 'local',
  providers: [
    { id: 'local', name: 'Local draft', type: 'local', endpoint: '', model: '', apiKey: '' },
    { id: 'grok', name: 'Grok / xAI', type: 'openai-compatible', endpoint: 'https://api.x.ai/v1/chat/completions', model: 'grok-4', apiKey: '' }
  ]
};
const clone = v => JSON.parse(JSON.stringify(v));
let workspace = load();
let aiSettings = loadAiSettings();
const $ = s => document.querySelector(s);
const esc = s => String(s || '').replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' })[c]);
const ticketById = id => workspace.tickets.find(t => t.id === id);
const openQuestions = () => workspace.questions.filter(q => !q.resolved);

function load() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); return saved?.version === 3 ? saved : clone(DEFAULT_WORKSPACE); } catch { return clone(DEFAULT_WORKSPACE); } }
function loadAiSettings() { try { const saved = JSON.parse(localStorage.getItem(AI_SETTINGS_KEY)); return saved?.providers ? {...clone(DEFAULT_AI_SETTINGS), ...saved, providers: mergeProviders(saved.providers)} : clone(DEFAULT_AI_SETTINGS); } catch { return clone(DEFAULT_AI_SETTINGS); } }
function mergeProviders(saved) { const defaults = clone(DEFAULT_AI_SETTINGS.providers), custom = saved.filter(p => !defaults.some(d => d.id === p.id)); return defaults.map(d => ({...d, ...(saved.find(p => p.id === d.id) || {})})).concat(custom); }
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(workspace)); $('#saveIndicator').textContent = '● Saved locally'; }
function saveAiSettings() { localStorage.setItem(AI_SETTINGS_KEY, JSON.stringify(aiSettings)); }
function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 2400); }
function depsDone(ticket) { return ticket.deps.every(id => ticketById(id)?.status === 'done'); }
function acProgress(t) { return [t.acceptanceCriteria.filter(a => a.done).length, t.acceptanceCriteria.length]; }
function statusText(s) { return ({todo:'Not started',in_progress:'In progress',done:'Done'})[s]; }

function renderAll() { renderCounts(); renderMap(); renderNextUp(); renderTicket(); renderDecisions(); renderQuestions(); }
function renderCounts() { const done = workspace.tickets.filter(t => t.status === 'done').length; $('#doneProgress').textContent = `${done} / ${workspace.tickets.length}`; $('#progressBar').style.width = `${done / workspace.tickets.length * 100}%`; $('#decisionCount').textContent = workspace.decisions.length; $('#questionCount').textContent = openQuestions().length; }
function renderNextUp() { const target = workspace.tickets.find(t => t.status !== 'done' && depsDone(t)); const el = $('#nextUp'); if (!target) { el.innerHTML = '<div class="next-card"><div><span class="next-kicker">PATH CLEAR</span><strong>Every ticket is complete.</strong></div></div>'; return; } const [complete,total] = acProgress(target); el.innerHTML = `<div class="next-card"><div><span class="next-kicker">NEXT UNBLOCKED TICKET</span><strong>${esc(target.id)} · ${esc(target.title)} <small>(${complete}/${total} AC)</small></strong></div><button class="button primary" data-open="${esc(target.id)}">Open ticket</button></div>`; el.querySelector('button').onclick = () => select(target.id); }

function levels() { const result = {}, degree = {}; workspace.tickets.forEach(t => degree[t.id] = t.deps.length); const queue = workspace.tickets.filter(t => !degree[t.id]); queue.forEach(t => result[t.id] = 0); while(queue.length){ const t = queue.shift(); workspace.tickets.filter(x => x.deps.includes(t.id)).forEach(x=>{result[x.id] = Math.max(result[x.id] || 0, result[t.id]+1); if(--degree[x.id]===0) queue.push(x); }); } workspace.tickets.forEach(t => result[t.id] ??= 0); return result; }
function renderMap() { const svg = $('#graph'), level = levels(), cols = []; workspace.tickets.forEach(t => (cols[level[t.id]] ||= []).push(t)); const w=190,h=93,gapX=235,gapY=123, margin=35, maxRows=Math.max(...cols.map(c=>c.length)); const fullW = margin*2+(cols.length-1)*gapX+w, fullH=margin*2+(maxRows-1)*gapY+h; svg.setAttribute('viewBox',`0 0 ${fullW} ${fullH}`); svg.setAttribute('width',fullW);svg.setAttribute('height',fullH);svg.innerHTML=''; const pos={}; cols.forEach((col,x)=>{const start=(fullH-(col.length*h+(col.length-1)*(gapY-h)))/2;col.forEach((t,y)=>pos[t.id]={x:margin+x*gapX,y:start+y*gapY});}); workspace.tickets.forEach(t=>t.deps.forEach(d=>{const a=pos[d],b=pos[t.id];if(!a||!b)return;const path=document.createElementNS('http://www.w3.org/2000/svg','path');const mid=(a.x+w+b.x)/2;path.setAttribute('d',`M ${a.x+w} ${a.y+h/2} C ${mid} ${a.y+h/2}, ${mid} ${b.y+h/2}, ${b.x} ${b.y+h/2}`);path.setAttribute('class',`edge ${ticketById(d).status==='done'?'done':''}`);svg.append(path);})); workspace.tickets.forEach(t=>{const p=pos[t.id],[done,total]=acProgress(t),g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class',`node ${t.status} ${workspace.selectedTicketId===t.id?'selected':''} ${t.status!=='done'&&depsDone(t)?'next':''}`);g.setAttribute('transform',`translate(${p.x},${p.y})`); const title=wrap(t.title,24);g.innerHTML=`<rect width="${w}" height="${h}" rx="8"/><text class="node-code" x="13" y="19">${esc(t.id)}</text><text class="node-meta" x="${w-13}" y="19" text-anchor="end">${t.effort} · ${effortXP[t.effort]}XP</text><text class="node-title" x="13" y="45">${esc(title[0])}</text>${title[1]?`<text class="node-title" x="13" y="61">${esc(title[1])}</text>`:''}<text class="node-status" x="13" y="80">${done}/${total} AC · ${t.status==='done'?'✓':statusText(t.status)}</text>`;g.onclick=()=>select(t.id);svg.append(g);}); }
function wrap(text, n){const a=['',''];text.split(' ').forEach(word=>{const i=(a[0]+' '+word).trim().length<=n?0:1;a[i]=(a[i]+' '+word).trim();});return a;}
function select(id){workspace.selectedTicketId=id;save();renderMap();renderTicket();}

function renderTicket() { const id=workspace.selectedTicketId,t=ticketById(id); $('#emptyTicket').hidden=!!t; $('#ticketDetails').hidden=!t;if(!t)return;const [done,total]=acProgress(t), deps=t.deps.map(x=>`${x} ${ticketById(x)?.status==='done'?'✓':''}`).join(''); const sessions=t.sessions.length?t.sessions.slice().reverse().map(s=>`<article class="session"><time>${esc(s.date)}</time><strong>${esc(s.summary)}</strong><p>${esc(s.nextSteps || '')}</p></article>`).join(''):'<p>No formal session reports yet.</p>'; $('#ticketDetails').innerHTML=`<div class="ticket-head"><span class="ticket-code">${esc(t.id)} · ${t.effort} · ${effortXP[t.effort]} XP</span><h2>${esc(t.title)}</h2><span class="status-pill ${t.status}">${statusText(t.status)}</span></div><div class="ticket-actions"><button class="button primary" data-action="brief">Copy session brief</button><button class="button" data-action="report">Paste session report</button><button class="button" data-action="status">Advance status</button><button class="button" data-action="edit">Edit ticket</button></div><section class="detail-section"><h3>OVERVIEW</h3><p>${esc(t.description)}</p></section><section class="detail-section"><h3>ACCEPTANCE CRITERIA · ${done}/${total}</h3><ul>${t.acceptanceCriteria.map((a,i)=>`<li><input data-ac="${i}" type="checkbox" ${a.done?'checked':''}><span>${esc(a.text)}</span></li>`).join('')}</ul></section><section class="detail-section"><h3>DEFINITION OF DONE</h3><p>${esc(t.definitionOfDone)}</p></section><section class="detail-section"><h3>TECHNICAL NOTES</h3><p>${esc(t.technicalNotes)}</p></section><section class="detail-section"><h3>DEPENDENCIES</h3><div class="dep-list">${t.deps.length?t.deps.map(d=>`<span class="chip">${esc(d)} ${ticketById(d)?.status==='done'?'✓':''}</span>`).join(''):'<span class="chip">No prerequisites</span>'}</div></section><section class="detail-section"><h3>SCRATCHPAD</h3><textarea id="scratchpad" placeholder="Loose thoughts, links, and reminders…">${esc(t.scratchpad)}</textarea></section><section class="detail-section"><h3>SESSION HISTORY</h3>${sessions}</section>`; $('#ticketDetails').querySelectorAll('[data-ac]').forEach(input=>input.onchange=()=>{t.acceptanceCriteria[input.dataset.ac].done=input.checked;save();renderAll();}); $('#scratchpad').oninput=e=>{t.scratchpad=e.target.value;save();}; $('#ticketDetails').querySelector('[data-action="brief"]').onclick=()=>copyBrief(t);$('#ticketDetails').querySelector('[data-action="report"]').onclick=()=>openReport(t);$('#ticketDetails').querySelector('[data-action="status"]').onclick=()=>{t.status=({todo:'in_progress',in_progress:'done',done:'todo'})[t.status];save();renderAll();};$('#ticketDetails').querySelector('[data-action="edit"]').onclick=()=>openTicketForm(t); }

function brief(t) { const deps=t.deps.length?t.deps.map(id=>`- ${id}: ${ticketById(id).status === 'done' ? '✅ done' : 'not complete'}`).join('\n'):'- None — this ticket is ready to start.'; const decisions=workspace.decisions.map(d=>`- ${d.id}: ${d.decision} — ${d.rationale}`).join('\n');const questions=openQuestions().map(q=>`- [${q.lane}] ${q.text}`).join('\n') || '- None';const last=t.sessions.at(-1);return `# DevTracker Session Brief\n\n## Ticket: ${t.id} — ${t.title}\nStatus: ${statusText(t.status)}\n\n### Goal\n${t.description}\n\n### Dependencies\n${deps}\n\n### Acceptance criteria\n${t.acceptanceCriteria.map(a=>`- [${a.done?'x':' '}] ${a.text}`).join('\n')}\n\n### Definition of done\n${t.definitionOfDone}\n\n### Technical notes\n${t.technicalNotes}\n\n### Project decisions\n${decisions}\n\n### Open questions\n${questions}\n${last?`\n### Last session\n${last.summary}\nNext: ${last.nextSteps}\n`:''}\n## End this session with this exact format\n\`\`\`session-report\nTicket: ${t.id}\nSummary: <what changed>\nCompleted AC: <comma-separated AC numbers, e.g. 1, 3>\nDecisions: <decision and rationale, or None>\nOpen Questions: <question, or None>\nNext Steps: <what should happen next>\nStatus: <todo | in_progress | done>\n\`\`\``; }
async function copyBrief(t){try{await navigator.clipboard.writeText(brief(t));toast('Session brief copied — paste it into your AI chat.');}catch{toast('Clipboard unavailable; copy from the dialog instead.');openTextDialog('Session brief',brief(t));}}
function openTextDialog(title,text){const d=$('#reportDialog');d.innerHTML=`<form method="dialog" class="dialog-body"><h2>${esc(title)}</h2><textarea class="report-format" style="min-height:340px">${esc(text)}</textarea><div class="dialog-actions"><button class="button primary">Close</button></div></form>`;d.showModal();}

function openReport(t){const d=$('#reportDialog');d.innerHTML=`<form class="dialog-body" id="reportForm"><h2>Paste Session Report</h2><p class="subcopy">Use the format from the session brief. Completed AC numbers and status are applied automatically.</p><div class="field"><label>Session report</label><textarea id="reportText" placeholder="Ticket: ${t.id}\nSummary: …\nCompleted AC: 1, 3\nDecisions: None\nOpen Questions: None\nNext Steps: …\nStatus: in_progress" required></textarea></div><div class="dialog-actions"><button class="button" type="button" data-close>Cancel</button><button class="button primary">Apply report</button></div></form>`;d.querySelector('[data-close]').onclick=()=>d.close();d.querySelector('form').onsubmit=e=>{e.preventDefault();applyReport(t,$('#reportText').value);d.close();};d.showModal();}
function field(text,key){return (text.match(new RegExp(`^${key}:\\s*(.*)$`,'im'))||[])[1]?.trim()||'';}
function applyReport(t,text){const ticket=field(text,'Ticket');if(ticket&&ticket!==t.id){toast(`Report names ${ticket}; it was not applied.`);return;}const summary=field(text,'Summary')||'Session report imported';const ac=field(text,'Completed AC');(ac.match(/\d+/g)||[]).map(Number).forEach(n=>{if(t.acceptanceCriteria[n-1])t.acceptanceCriteria[n-1].done=true;});const status=field(text,'Status');if(['todo','in_progress','done'].includes(status))t.status=status;const date=new Date().toISOString().slice(0,10);t.sessions.push({date,summary,nextSteps:field(text,'Next Steps'),raw:text});const decision=field(text,'Decisions');if(decision&&decision.toLowerCase()!=='none')workspace.decisions.push({id:`ADR-${String(workspace.decisions.length+1).padStart(3,'0')}`,date,decision,rationale:'Captured from session report.'});const question=field(text,'Open Questions');if(question&&question.toLowerCase()!=='none')workspace.questions.push({id:`Q-${String(workspace.questions.length+1).padStart(3,'0')}`,lane:'agent',text:question,resolved:false});save();renderAll();toast('Session report applied. Context is now saved.');}

function ticketIntent(form) { const id=form.elements.id.value.trim(), title=form.elements.title.value.trim(), desc=form.elements.description.value.trim(); return { id, title, seed: desc || title || id || 'new engineering ticket' }; }
function aiEnhancedTicketDraft(form) { const intent=ticketIntent(form), name=intent.title || intent.id || 'this ticket'; const existingDeps=workspace.tickets.filter(t=>t.status!=='done').slice(0,3).map(t=>t.id).join(', ') || 'None'; return {
  description: `Deliver ${name} as a narrow, testable engineering change. Clarify the expected behavior, touch only the necessary project surface, and leave enough implementation notes for a future AI session to continue without re-discovery.`,
  ac: [`The intended behavior for ${name} is implemented and visible through the relevant UI, API, or workflow`, 'Validation, empty states, and failure paths are handled with actionable feedback', 'The change is covered by a focused manual or automated verification step', 'Session notes capture any important follow-up, tradeoff, or decision'].join('\n'),
  dod: `${name} is complete when the implementation works from a fresh reload, the verification path is documented, and the ticket brief gives the next AI session enough context to resume safely.`,
  notes: `AI enhancement draft:\n- Suggested current dependencies to consider: ${existingDeps}\n- Keep the ticket scoped to one shippable behavior.\n- Prefer explicit acceptance criteria over broad intent.\n- At session end, paste a session report so progress, decisions, and questions stay synchronized.`
}; }
function activeProvider(){return aiSettings.providers.find(p=>p.id===aiSettings.activeProviderId)||aiSettings.providers[0];}
function applyTicketDraft(form,draft){const fields={description:'description',ac:'ac',dod:'dod',notes:'notes'};Object.entries(fields).forEach(([key,name])=>{if(draft[key]&&!form.elements[name].value.trim())form.elements[name].value=draft[key];});}
function ticketEnhancePrompt(form){const intent=ticketIntent(form), open=workspace.questions.filter(q=>!q.resolved).map(q=>q.text).join('; ')||'None';return `You are helping draft a DevTracker engineering ticket. Return only JSON with keys description, ac, dod, notes. ac must be one string with one acceptance criterion per line.\n\nProject: ${workspace.project.name}\nTicket code: ${intent.id || 'unset'}\nTicket title: ${intent.title || 'unset'}\nSeed description: ${intent.seed}\nExisting ticket ids: ${workspace.tickets.map(t=>`${t.id}: ${t.title}`).join('; ')}\nOpen project questions: ${open}\n\nMake the ticket implementation-ready for a human plus AI coding session. Keep it concise, concrete, and testable.`;}
function parseAiDraft(text){const match=text.match(/\{[\s\S]*\}/);if(!match)throw Error('No JSON object returned.');const data=JSON.parse(match[0]);return {description:data.description||'',ac:Array.isArray(data.ac)?data.ac.join('\n'):(data.ac||''),dod:data.dod||data.definitionOfDone||'',notes:data.notes||data.technicalNotes||''};}
async function requestAiDraft(form,provider){const res=await fetch(provider.endpoint,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${provider.apiKey}`},body:JSON.stringify({model:provider.model,messages:[{role:'system',content:'Return compact valid JSON only. Do not wrap it in markdown.'},{role:'user',content:ticketEnhancePrompt(form)}],temperature:.25})});if(!res.ok)throw Error(`AI request failed (${res.status})`);const data=await res.json();const text=data.choices?.[0]?.message?.content||data.output_text||'';return parseAiDraft(text);}
async function enhanceTicketForm(form) { const provider=activeProvider(); if(provider.type==='local'||!provider.apiKey||!provider.endpoint){applyTicketDraft(form,aiEnhancedTicketDraft(form));toast(provider.type==='local'?'Local AI-style draft added.':'Provider is missing a key or endpoint; local draft added.');return;} const button=form.querySelector('[data-ai-enhance]');button.disabled=true;button.textContent='Enhancing...';try{applyTicketDraft(form,await requestAiDraft(form,provider));toast(`Enhanced with ${provider.name}.`);}catch(err){applyTicketDraft(form,aiEnhancedTicketDraft(form));toast(`${err.message} Local draft added instead.`);}finally{button.disabled=false;button.textContent='Enhance';} }

function openTicketForm(existing){const t=existing||{id:'',title:'',effort:'S',line:'default',deps:[],description:'',definitionOfDone:'',technicalNotes:'',acceptanceCriteria:[]}, provider=activeProvider();const d=$('#ticketDialog');d.innerHTML=`<form class="dialog-body" id="ticketForm"><h2>${existing?'Edit':'New'} ticket</h2>${existing?'':`<div class="ai-panel"><div><strong>AI enhancement</strong><p>Active: ${esc(provider.name)}${provider.type!=='local'&&!provider.apiKey?' - add API key in settings':''}</p></div><div class="ai-actions"><button class="button" type="button" data-ai-settings>Settings</button><button class="button" type="button" data-ai-enhance>Enhance</button></div></div>`}<div class="form-grid"><div class="field"><label>Ticket code</label><input name="id" value="${esc(t.id)}" ${existing?'readonly':''} required></div><div class="field"><label>Effort</label><select name="effort">${['XS','S','M','L'].map(x=>`<option ${x===t.effort?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="field"><label>Title</label><input name="title" value="${esc(t.title)}" required></div><div class="field"><label>Description</label><textarea name="description">${esc(t.description)}</textarea></div><div class="field"><label>Acceptance criteria (one per line)</label><textarea name="ac">${esc(t.acceptanceCriteria.map(a=>a.text).join('\n'))}</textarea></div><div class="field"><label>Definition of done</label><textarea name="dod">${esc(t.definitionOfDone)}</textarea></div><div class="field"><label>Technical notes</label><textarea name="notes">${esc(t.technicalNotes)}</textarea></div><div class="dialog-actions"><button class="button" type="button" data-close>Cancel</button><button class="button primary">Save ticket</button></div></form>`;d.querySelector('[data-close]').onclick=()=>d.close();const enhance=d.querySelector('[data-ai-enhance]');if(enhance)enhance.onclick=()=>enhanceTicketForm(d.querySelector('form'));const settings=d.querySelector('[data-ai-settings]');if(settings)settings.onclick=()=>openAiSettings();d.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),item={...t,id:f.get('id').trim(),title:f.get('title').trim(),effort:f.get('effort'),description:f.get('description'),definitionOfDone:f.get('dod'),technicalNotes:f.get('notes'),acceptanceCriteria:f.get('ac').split('\n').filter(Boolean).map((text,i)=>({text,done:t.acceptanceCriteria[i]?.done||false}))};if(!item.id||(!existing&&ticketById(item.id))){toast('Use a unique ticket code.');return;}if(existing)Object.assign(existing,item);else workspace.tickets.push(item);workspace.selectedTicketId=item.id;save();d.close();renderAll();};d.showModal();}

function openAiSettings(){const d=$('#aiDialog'), provider=activeProvider();d.innerHTML=`<form class="dialog-body" id="aiForm"><h2>AI settings</h2><p class="subcopy">Use Local draft with no key, or add an OpenAI-compatible provider such as Grok.</p><div class="field"><label>Active provider</label><select name="active">${aiSettings.providers.map(p=>`<option value="${esc(p.id)}" ${p.id===provider.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><div class="form-grid"><div class="field"><label>Name</label><input name="name" value="${esc(provider.name)}" ${provider.id==='local'?'readonly':''}></div><div class="field"><label>Model</label><input name="model" value="${esc(provider.model)}" ${provider.id==='local'?'readonly':''} placeholder="grok-4"></div></div><div class="field"><label>Endpoint</label><input name="endpoint" value="${esc(provider.endpoint)}" ${provider.id==='local'?'readonly':''} placeholder="https://api.x.ai/v1/chat/completions"></div><div class="field"><label>API key</label><input name="apiKey" type="password" value="${esc(provider.apiKey)}" ${provider.id==='local'?'readonly':''} placeholder="Paste your key here"></div><p class="settings-note">Keys are saved in this browser only. Use this for local/private workspaces, not shared browsers.</p><div class="dialog-actions"><button class="button" type="button" data-add-provider>Add custom provider</button><button class="button" type="button" data-close>Cancel</button><button class="button primary">Save settings</button></div></form>`;const form=d.querySelector('form');form.elements.active.onchange=()=>{aiSettings.activeProviderId=form.elements.active.value;saveAiSettings();openAiSettings();};d.querySelector('[data-add-provider]').onclick=()=>{const id=`custom-${Date.now()}`;aiSettings.providers.push({id,name:'Custom AI',type:'openai-compatible',endpoint:'',model:'',apiKey:''});aiSettings.activeProviderId=id;saveAiSettings();openAiSettings();};d.querySelector('[data-close]').onclick=()=>d.close();form.onsubmit=e=>{e.preventDefault();const p=activeProvider();if(p.id!=='local'){p.name=form.elements.name.value.trim()||p.name;p.model=form.elements.model.value.trim();p.endpoint=form.elements.endpoint.value.trim();p.apiKey=form.elements.apiKey.value.trim();}aiSettings.activeProviderId=form.elements.active.value;saveAiSettings();d.close();toast('AI settings saved.');};if(!d.open)d.showModal();}

function renderDecisions(){const el=$('#decisionsView');el.innerHTML=`<div class="view-head"><div><p class="eyebrow">ADR-LITE</p><h1>Project decisions</h1><p class="subcopy">Settled choices automatically travel with every AI session brief.</p></div><button class="button primary" id="addDecision">+ Decision</button></div><div class="list-card">${workspace.decisions.map(d=>`<article class="list-row"><span class="list-meta">${esc(d.id)} · ${esc(d.date)}</span><strong>${esc(d.decision)}</strong><p>${esc(d.rationale)}</p></article>`).join('')}</div>`;$('#addDecision').onclick=()=>openSimpleForm('decision');}
function renderQuestions(){const el=$('#questionsView');el.innerHTML=`<div class="view-head"><div><p class="eyebrow">CONTEXT QUEUE</p><h1>Open questions</h1><p class="subcopy">Questions remain visible in briefs until someone resolves them.</p></div><button class="button primary" id="addQuestion">+ Question</button></div><div class="list-card">${workspace.questions.map(q=>`<article class="list-row"><span class="question-lane">${q.lane} needs to decide</span><strong>${esc(q.text)}</strong><p><button class="button" data-resolve="${q.id}">${q.resolved?'Reopen':'Resolve'}</button></p></article>`).join('')}</div>`;$('#addQuestion').onclick=()=>openSimpleForm('question');el.querySelectorAll('[data-resolve]').forEach(b=>b.onclick=()=>{const q=workspace.questions.find(q=>q.id===b.dataset.resolve);q.resolved=!q.resolved;save();renderAll();});}
function openSimpleForm(kind){const d=kind==='decision'?$('#decisionDialog'):$('#questionDialog');const title=kind==='decision'?'Add a decision':'Add an open question';d.innerHTML=`<form class="dialog-body"><h2>${title}</h2><div class="field"><label>${kind==='decision'?'Decision':'Question'}</label><textarea name="text" required></textarea></div>${kind==='decision'?'<div class="field"><label>Rationale</label><textarea name="reason" required></textarea></div>':''}<div class="dialog-actions"><button class="button" type="button" data-close>Cancel</button><button class="button primary">Add</button></div></form>`;d.querySelector('[data-close]').onclick=()=>d.close();d.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),date=new Date().toISOString().slice(0,10);if(kind==='decision')workspace.decisions.push({id:`ADR-${String(workspace.decisions.length+1).padStart(3,'0')}`,date,decision:f.get('text'),rationale:f.get('reason')});else workspace.questions.push({id:`Q-${String(workspace.questions.length+1).padStart(3,'0')}`,lane:'human',text:f.get('text'),resolved:false});save();d.close();renderAll();};d.showModal();}

function setView(view){['map','decisions','questions'].forEach(v=>{$(`#${v}View`).hidden=v!==view;if(v==='map')$('#ticketPanel').hidden=false;});if(view!=='map')$('#ticketPanel').hidden=true;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));}
function exportState(){const blob=new Blob([JSON.stringify(workspace,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='devtracker-workspace.json';a.click();URL.revokeObjectURL(a.href);toast('Workspace exported as JSON.');}
function importState(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data.tickets))throw Error();workspace={...clone(DEFAULT_WORKSPACE),...data,version:3};save();renderAll();toast('Workspace imported.');}catch{toast('That file is not a valid DevTracker workspace.');}};reader.readAsText(file);}

$('#newTicketButton').onclick=()=>openTicketForm();$('#aiSettingsButton').onclick=()=>openAiSettings();$('#exportButton').onclick=exportState;$('#importButton').onclick=()=>$('#importInput').click();$('#importInput').onchange=e=>e.target.files[0]&&importState(e.target.files[0]);document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));renderAll();
